server:
  port: 7201

spring:
  application:
    name: eurekaserver

eureka:
  instance:
    hostname:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
