spring:
  application:
    name: employeeservice
  config:
    import: optional:configserver:http://localhost:7200
  data:
    mongodb:
      url: mongodb://27017/employeeDB
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
